apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-microservice.fullname" . }}-cm
  labels:
    {{- include "java-microservice.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
