apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-microservice.fullname" . }}
  labels:
    {{- include "java-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "java-microservice.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
