image:
  repository: microtema/process-reporting-service
  tag: "7.1.3"

app:
  name: customer-service
  port: 8080
  contextPath: "/customer"
  javaOpts: "-Dspring.profiles.active=dev"

env:
  SX_PRING_DATASOURCE_URL: "jdbc:postgresql://postgres.dev.svc:5432/customer"
  SX_SPRING_DATASOURCE_USERNAME: "customer_app"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: false