image:
  repository: springio/gs-actuator-service
  tag: "latest"

app:
  name: customer-service
  port: 8080
  contextPath: "/customer"
  javaOpts: "-Dspring.profiles.active=dev"

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.dev.svc:5432/customer"
  SPRING_DATASOURCE_USERNAME: "customer_app"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: false