image:
  repository: myacr.azurecr.io/invoice-service
  tag: "1.0.0"

app:
  name: invoice-service
  port: 8080
  contextPath: "/invoice"
  javaOpts: "-Dspring.profiles.active=dev"

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.dev.svc:5432/invoice"
  SPRING_DATASOURCE_USERNAME: "invoice_app"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: false