image:
  repository: microtema/process-reporting-service
  tag: "7.0.0"

app:
  name: customer-service
  port: 8080
  contextPath: "/reporting-service"
  javaOpts: "-Dspring.profiles.active=prod"
  readinessPath: "/rest/api/time-range"
  livenessPath: "/rest/api/time-range"

env:
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: ""
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_JPA_DATABASE: "H2"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: false

securityContext:
  readOnlyRootFilesystem: false