image:
  repository: myacr.azurecr.io/order-service
  tag: "1.0.0"

app:
  name: order-service
  port: 8080
  contextPath: "/order"
  javaOpts: "-Dspring.profiles.active=dev"

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.dev.svc:5432/order"
  SPRING_DATASOURCE_USERNAME: "order_app"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: false