name: "reporting-frontend"
namespace: "mate-reporting-frontend-dev-weu-001"

image:
  repository: microtema/process-reporting-frontend
  tag: "7.0.0"

replicaCount: 1

app:
  port: 8080
  contextPath: "/"
  javaOpts: "-Dspring.profiles.active=prod"
  readinessPath: "/"
  livenessPath: "/"

env:
  REST_API_SERVERS: "http://reporting-frontend-service:8080/reporting-service"

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: false

securityContext:
  readOnlyRootFilesystem: false